import Link from "next/link";
import { 
  FileSpreadsheet, 
  FileText, 
  CheckCircle2, 
  ArrowRight, 
  Clock, 
  Sparkles, 
  ShieldCheck, 
  Zap,
  Search,
  Target
} from "lucide-react";
import { FadeIn } from "@/components/animations";

const auditFeatures = [
  {
    title: "1. Technical Crawl & Indexing Health",
    desc: "Detailed audit of status codes, canonicals, schema tags, crawl bloat, and core web vital bottlenecks stopping your pages from ranking.",
  },
  {
    title: "2. Backlink Quality & Toxic Link Audit",
    desc: "Complete evaluation of your current referring domains, anchor text distribution, domain rating trajectory, and spam risks.",
  },
  {
    title: "3. Competitor Link & Keyword Gap Matrix",
    desc: "Side-by-side gap analysis comparing your top 3 SERP competitors to reveal easy-win keyword opportunities and high-authority link targets.",
  },
  {
    title: "4. Prioritized 90-Day Execution Roadmap",
    desc: "A custom, no-fluff action plan outlining exactly which technical fixes, on-page changes, and link campaigns to run first for maximum ROI.",
  },
];

export function SeoAuditSpotlightSection() {
  return (
    <section className="section bg-card/40 relative overflow-hidden border-t border-border/60" aria-labelledby="audit-spotlight-heading">
      {/* Background decorations */}
      <div className="absolute top-1/2 left-0 w-80 h-80 bg-primary/10 rounded-full blur-3xl pointer-events-none -z-10" />
      <div className="absolute bottom-0 right-10 w-96 h-96 bg-emerald-500/5 rounded-full blur-3xl pointer-events-none -z-10" />

      <div className="container-wide">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-10 lg:gap-14 items-center">
          
          {/* Left Column: Copy & Value Proposition */}
          <div className="lg:col-span-7 space-y-6 text-center lg:text-left">
            <FadeIn>
              <div className="inline-flex items-center gap-2 px-3.5 py-1 rounded-full border border-primary/20 bg-primary/5 text-primary text-xs font-semibold uppercase tracking-wider mb-2">
                <Sparkles className="w-3.5 h-3.5" />
                Featured Low-Risk Entry Point
              </div>
              
              <h2 id="audit-spotlight-heading" className="text-2xl sm:text-3xl lg:text-4xl font-extrabold tracking-tight text-foreground leading-tight">
                Stop Guessing Your SEO. Get a <br className="hidden sm:inline" />
                <span className="text-primary">Comprehensive $15 Manual Audit.</span>
              </h2>

              <p className="text-sm sm:text-base text-muted-foreground leading-relaxed pt-1 max-w-xl mx-auto lg:mx-0">
                Most SEO audits are generic 50-page automated PDF dumps generated by software. 
                Our $15 audit is a human-analyzed, bespoke teardown built using live Ahrefs and SEMrush data, delivered in 24-48 hours.
              </p>
            </FadeIn>

            {/* Feature points */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 pt-2">
              {auditFeatures.map((feat, idx) => (
                <div key={idx} className="p-4 rounded-xl border border-border/60 bg-background/80 text-left space-y-1">
                  <div className="flex items-center gap-2 font-bold text-xs sm:text-sm text-foreground">
                    <CheckCircle2 className="w-4 h-4 text-primary shrink-0" />
                    <span>{feat.title}</span>
                  </div>
                  <p className="text-xs text-muted-foreground leading-relaxed pl-6">
                    {feat.desc}
                  </p>
                </div>
              ))}
            </div>

            {/* CTAs */}
            <div className="flex flex-col sm:flex-row items-center justify-center lg:justify-start gap-4 pt-3">
              <Link href="/seo-audit" className="w-full sm:w-auto">
                <button className="w-full sm:w-auto px-8 py-3.5 rounded-full bg-primary text-primary-foreground font-bold text-sm hover:bg-primary/90 transition-all shadow-lg shadow-primary/20 flex items-center justify-center gap-2">
                  <span>Order Your $15 Audit</span>
                  <ArrowRight className="w-4 h-4" />
                </button>
              </Link>
              <div className="flex flex-wrap items-center justify-center lg:justify-start gap-2 text-xs font-semibold text-muted-foreground">
                <div className="flex items-center gap-1.5">
                  <Clock className="w-4 h-4 text-primary shrink-0" />
                  <span>24–48h Turnaround</span>
                </div>
                <span className="text-border hidden sm:inline">•</span>
                <div className="flex items-center gap-1.5">
                  <ShieldCheck className="w-4 h-4 text-primary shrink-0" />
                  <span>100% Credited on Retainers</span>
                </div>
              </div>
            </div>
          </div>

          {/* Right Column: Visual Card Showcase */}
          <div className="lg:col-span-5">
            <FadeIn delay={0.2}>
              <div className="relative rounded-3xl border-2 border-primary/20 bg-gradient-to-br from-card via-card/90 to-background p-6 sm:p-8 shadow-2xl">
                
                {/* Top Badge Banner */}
                <div className="flex items-center justify-between pb-6 border-b border-border">
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 rounded-xl bg-primary/10 border border-primary/20 flex items-center justify-center text-primary font-black text-sm">
                      sr.
                    </div>
                    <div>
                      <h4 className="text-sm font-bold text-foreground">Custom SEO Teardown</h4>
                      <p className="text-xs text-muted-foreground">Executive PDF &amp; Google Sheet</p>
                    </div>
                  </div>
                  <div className="text-right">
                    <span className="text-2xl font-black text-primary">$15</span>
                    <span className="text-[11px] text-muted-foreground block font-medium">One-Time Fee</span>
                  </div>
                </div>

                {/* Deliverables Checklist */}
                <div className="space-y-3.5 py-6">
                  <div className="flex items-center justify-between p-3 rounded-xl bg-muted/40 border border-border/40 text-xs">
                    <div className="flex items-center gap-2.5">
                      <FileText className="w-4 h-4 text-primary shrink-0" />
                      <span className="font-semibold text-foreground">Actionable Strategic Report</span>
                    </div>
                    <span className="text-muted-foreground font-mono">PDF</span>
                  </div>

                  <div className="flex items-center justify-between p-3 rounded-xl bg-muted/40 border border-border/40 text-xs">
                    <div className="flex items-center gap-2.5">
                      <FileSpreadsheet className="w-4 h-4 text-emerald-400 shrink-0" />
                      <span className="font-semibold text-foreground">Competitor Link Gap Raw Data</span>
                    </div>
                    <span className="text-muted-foreground font-mono">Sheets</span>
                  </div>

                  <div className="flex items-center justify-between p-3 rounded-xl bg-muted/40 border border-border/40 text-xs">
                    <div className="flex items-center gap-2.5">
                      <Target className="w-4 h-4 text-amber-400 shrink-0" />
                      <span className="font-semibold text-foreground">Top 5 Target Keyword Roadmap</span>
                    </div>
                    <span className="text-muted-foreground font-mono">Curated</span>
                  </div>

                  <div className="flex items-center justify-between p-3 rounded-xl bg-muted/40 border border-border/40 text-xs">
                    <div className="flex items-center gap-2.5">
                      <Zap className="w-4 h-4 text-primary shrink-0" />
                      <span className="font-semibold text-foreground">Quick-Win Technical Fixes</span>
                    </div>
                    <span className="text-primary font-bold">High-ROI</span>
                  </div>
                </div>

                {/* Guarantee Note */}
                <div className="p-4 rounded-xl bg-primary/10 border border-primary/20 text-center">
                  <p className="text-xs font-semibold text-foreground">
                    💡 <strong>100% Risk-Free:</strong> The entire $15 is credited directly toward any future monthly link building or SEO sprint.
                  </p>
                </div>

                <div className="mt-5">
                  <Link href="/seo-audit" className="w-full block">
                    <button className="w-full py-3 rounded-xl bg-foreground text-background dark:bg-primary dark:text-primary-foreground font-bold text-xs sm:text-sm hover:opacity-90 transition-opacity flex items-center justify-center gap-2">
                      <span>View Full Audit Details &amp; Sample</span>
                      <ArrowRight className="w-3.5 h-3.5" />
                    </button>
                  </Link>
                </div>

              </div>
            </FadeIn>
          </div>

        </div>
      </div>
    </section>
  );
}
